export const APP_NAME = 'Huaji'
export const APP_NAME_EN = 'Huaji'
export const APP_ORG = 'Huabo'
export const APP_TAGLINE = 'Huabo local WeChat archive'
export const APP_WATERMARK = 'Exported by Huaji'
export const APP_ATTRIBUTION = 'Based on the open-source project CipherTalk (CC BY-NC-SA 4.0). Original authors must be credited.'
